networks:
  proxy:
    name: proxy
    driver: bridge

volumes:
  certs:
  vhost:
  html:
  dhparam:
  acme:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks: [proxy]
    environment:
      ENABLE_IPV6: "true" # Debian 12 supports it out of the box
      SSL_POLICY: "Mozilla-Modern"

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./nginx-config:/etc/nginx/conf.d/custom:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: unless-stopped
    networks: [proxy]
    depends_on: [nginx-proxy]
    environment:
      DEFAULT_EMAIL: "hello@yewenjin.com" # change me
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh

  chatroom-web:
    image: nginx:alpine
    container_name: chatroom-web
    restart: unless-stopped
    networks: [proxy]
    environment:
      VIRTUAL_HOST: chat.datadadaist.space
      LETSENCRYPT_HOST: chat.datadadaist.space
      LETSENCRYPT_EMAIL: hello@yewenjin.com
    volumes:
      - /home/yewen/voidspace/Void-Space-Chatroom/dist:/usr/share/nginx/html:ro
      - ./nginx-config/chatroom-web.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
